// AUTO-GENERATED by scripts/inject-version.ts — DO NOT EDIT.
// Regenerated on every build; values reflect the artifacts being shipped.

export const BUNDLE_VERSION = "0.15.0";
export const WORKER_HASH = "sha256:04815f4899e502175266dfbecb8ff110d3f79aef8585249cb56ab27adf46bd3c";
export const ADMIN_HASH = "sha256:c8256fcec6330126c78343d90b341b63bba3f4a1e7362919d7866ca98af993fc";
export const LIFF_HASH = "sha256:0c830a1e5936e8eabcf86abcdcb5b34471bfc40595e08b20f4ad615402b2224c";
export const RELEASED_AT = "2026-07-02T13:06:18.057Z";
