-- A form-scoped generation makes duplicate-group validation and the row review
-- marker one atomic compare-and-set. Only fields that can change membership,
-- content hints, deletion state, or review state bump the generation.

ALTER TABLE formaloo_forms
  ADD COLUMN submission_duplicate_review_generation INTEGER NOT NULL DEFAULT 0;

CREATE TRIGGER IF NOT EXISTS trg_internal_submission_duplicate_review_generation_insert AFTER INSERT ON internal_form_submissions BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = NEW.form_id; END;
CREATE TRIGGER IF NOT EXISTS trg_internal_submission_duplicate_review_generation_update AFTER UPDATE OF form_id, friend_id, answers_json, deleted_at ON internal_form_submissions WHEN OLD.form_id IS NOT NEW.form_id OR OLD.friend_id IS NOT NEW.friend_id OR OLD.answers_json IS NOT NEW.answers_json OR OLD.deleted_at IS NOT NEW.deleted_at BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = OLD.form_id; UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = NEW.form_id AND NEW.form_id IS NOT OLD.form_id; END;
CREATE TRIGGER IF NOT EXISTS trg_internal_submission_duplicate_review_generation_delete AFTER DELETE ON internal_form_submissions BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = OLD.form_id; END;

CREATE TRIGGER IF NOT EXISTS trg_formaloo_submission_duplicate_review_generation_insert AFTER INSERT ON formaloo_submissions BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = NEW.form_id; END;
CREATE TRIGGER IF NOT EXISTS trg_formaloo_submission_duplicate_review_generation_update AFTER UPDATE OF form_id, friend_id, answers_json ON formaloo_submissions WHEN OLD.form_id IS NOT NEW.form_id OR OLD.friend_id IS NOT NEW.friend_id OR OLD.answers_json IS NOT NEW.answers_json BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = OLD.form_id; UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = NEW.form_id AND NEW.form_id IS NOT OLD.form_id; END;
CREATE TRIGGER IF NOT EXISTS trg_formaloo_submission_duplicate_review_generation_delete AFTER DELETE ON formaloo_submissions BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = OLD.form_id; END;

CREATE TRIGGER IF NOT EXISTS trg_formaloo_field_duplicate_review_generation_insert AFTER INSERT ON formaloo_field_map BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = NEW.form_id; END;
CREATE TRIGGER IF NOT EXISTS trg_formaloo_field_duplicate_review_generation_update AFTER UPDATE OF form_id, formaloo_field_slug, field_type, label, position ON formaloo_field_map WHEN OLD.form_id IS NOT NEW.form_id OR OLD.formaloo_field_slug IS NOT NEW.formaloo_field_slug OR OLD.field_type IS NOT NEW.field_type OR OLD.label IS NOT NEW.label OR OLD.position IS NOT NEW.position BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = OLD.form_id; UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = NEW.form_id AND NEW.form_id IS NOT OLD.form_id; END;
CREATE TRIGGER IF NOT EXISTS trg_formaloo_field_duplicate_review_generation_delete AFTER DELETE ON formaloo_field_map BEGIN UPDATE formaloo_forms SET submission_duplicate_review_generation = submission_duplicate_review_generation + 1 WHERE id = OLD.form_id; END;
